package com.lyl.webElf.dao;

import com.lyl.webElf.domain.GuessResult;
import com.lyl.webElf.domain.GuessResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuessResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    long countByExample(GuessResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    int deleteByExample(GuessResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    int insert(GuessResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    int insertSelective(GuessResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    List<GuessResult> selectByExampleWithBLOBs(GuessResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    List<GuessResult> selectByExample(GuessResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") GuessResult record, @Param("example") GuessResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") GuessResult record, @Param("example") GuessResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    int updateByExample(@Param("record") GuessResult record, @Param("example") GuessResultExample example);
}