package com.lyl.webElf.dao;

import com.lyl.webElf.domain.LiveItem;
import com.lyl.webElf.domain.LiveItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    long countByExample(LiveItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    int deleteByExample(LiveItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    int insert(LiveItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    int insertSelective(LiveItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    List<LiveItem> selectByExample(LiveItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") LiveItem record, @Param("example") LiveItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_item
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    int updateByExample(@Param("record") LiveItem record, @Param("example") LiveItemExample example);
}