package com.lyl.webElf.domain;

import java.util.ArrayList;
import java.util.List;

public class GuessResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public GuessResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameidIsNull() {
            addCriterion("gameId is null");
            return (Criteria) this;
        }

        public Criteria andGameidIsNotNull() {
            addCriterion("gameId is not null");
            return (Criteria) this;
        }

        public Criteria andGameidEqualTo(String value) {
            addCriterion("gameId =", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotEqualTo(String value) {
            addCriterion("gameId <>", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidGreaterThan(String value) {
            addCriterion("gameId >", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidGreaterThanOrEqualTo(String value) {
            addCriterion("gameId >=", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLessThan(String value) {
            addCriterion("gameId <", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLessThanOrEqualTo(String value) {
            addCriterion("gameId <=", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLike(String value) {
            addCriterion("gameId like", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotLike(String value) {
            addCriterion("gameId not like", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidIn(List<String> values) {
            addCriterion("gameId in", values, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotIn(List<String> values) {
            addCriterion("gameId not in", values, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidBetween(String value1, String value2) {
            addCriterion("gameId between", value1, value2, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotBetween(String value1, String value2) {
            addCriterion("gameId not between", value1, value2, "gameid");
            return (Criteria) this;
        }

        public Criteria andEndrate1IsNull() {
            addCriterion("endRate1 is null");
            return (Criteria) this;
        }

        public Criteria andEndrate1IsNotNull() {
            addCriterion("endRate1 is not null");
            return (Criteria) this;
        }

        public Criteria andEndrate1EqualTo(Long value) {
            addCriterion("endRate1 =", value, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1NotEqualTo(Long value) {
            addCriterion("endRate1 <>", value, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1GreaterThan(Long value) {
            addCriterion("endRate1 >", value, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1GreaterThanOrEqualTo(Long value) {
            addCriterion("endRate1 >=", value, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1LessThan(Long value) {
            addCriterion("endRate1 <", value, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1LessThanOrEqualTo(Long value) {
            addCriterion("endRate1 <=", value, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1In(List<Long> values) {
            addCriterion("endRate1 in", values, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1NotIn(List<Long> values) {
            addCriterion("endRate1 not in", values, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1Between(Long value1, Long value2) {
            addCriterion("endRate1 between", value1, value2, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndrate1NotBetween(Long value1, Long value2) {
            addCriterion("endRate1 not between", value1, value2, "endrate1");
            return (Criteria) this;
        }

        public Criteria andEndnum1IsNull() {
            addCriterion("endNum1 is null");
            return (Criteria) this;
        }

        public Criteria andEndnum1IsNotNull() {
            addCriterion("endNum1 is not null");
            return (Criteria) this;
        }

        public Criteria andEndnum1EqualTo(Integer value) {
            addCriterion("endNum1 =", value, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1NotEqualTo(Integer value) {
            addCriterion("endNum1 <>", value, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1GreaterThan(Integer value) {
            addCriterion("endNum1 >", value, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1GreaterThanOrEqualTo(Integer value) {
            addCriterion("endNum1 >=", value, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1LessThan(Integer value) {
            addCriterion("endNum1 <", value, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1LessThanOrEqualTo(Integer value) {
            addCriterion("endNum1 <=", value, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1In(List<Integer> values) {
            addCriterion("endNum1 in", values, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1NotIn(List<Integer> values) {
            addCriterion("endNum1 not in", values, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1Between(Integer value1, Integer value2) {
            addCriterion("endNum1 between", value1, value2, "endnum1");
            return (Criteria) this;
        }

        public Criteria andEndnum1NotBetween(Integer value1, Integer value2) {
            addCriterion("endNum1 not between", value1, value2, "endnum1");
            return (Criteria) this;
        }

        public Criteria andGuessname1IsNull() {
            addCriterion("guessName1 is null");
            return (Criteria) this;
        }

        public Criteria andGuessname1IsNotNull() {
            addCriterion("guessName1 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessname1EqualTo(String value) {
            addCriterion("guessName1 =", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotEqualTo(String value) {
            addCriterion("guessName1 <>", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1GreaterThan(String value) {
            addCriterion("guessName1 >", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1GreaterThanOrEqualTo(String value) {
            addCriterion("guessName1 >=", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1LessThan(String value) {
            addCriterion("guessName1 <", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1LessThanOrEqualTo(String value) {
            addCriterion("guessName1 <=", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1Like(String value) {
            addCriterion("guessName1 like", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotLike(String value) {
            addCriterion("guessName1 not like", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1In(List<String> values) {
            addCriterion("guessName1 in", values, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotIn(List<String> values) {
            addCriterion("guessName1 not in", values, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1Between(String value1, String value2) {
            addCriterion("guessName1 between", value1, value2, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotBetween(String value1, String value2) {
            addCriterion("guessName1 not between", value1, value2, "guessname1");
            return (Criteria) this;
        }

        public Criteria andResult1IsNull() {
            addCriterion("result1 is null");
            return (Criteria) this;
        }

        public Criteria andResult1IsNotNull() {
            addCriterion("result1 is not null");
            return (Criteria) this;
        }

        public Criteria andResult1EqualTo(String value) {
            addCriterion("result1 =", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1NotEqualTo(String value) {
            addCriterion("result1 <>", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1GreaterThan(String value) {
            addCriterion("result1 >", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1GreaterThanOrEqualTo(String value) {
            addCriterion("result1 >=", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1LessThan(String value) {
            addCriterion("result1 <", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1LessThanOrEqualTo(String value) {
            addCriterion("result1 <=", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1Like(String value) {
            addCriterion("result1 like", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1NotLike(String value) {
            addCriterion("result1 not like", value, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1In(List<String> values) {
            addCriterion("result1 in", values, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1NotIn(List<String> values) {
            addCriterion("result1 not in", values, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1Between(String value1, String value2) {
            addCriterion("result1 between", value1, value2, "result1");
            return (Criteria) this;
        }

        public Criteria andResult1NotBetween(String value1, String value2) {
            addCriterion("result1 not between", value1, value2, "result1");
            return (Criteria) this;
        }

        public Criteria andEndrate2IsNull() {
            addCriterion("endRate2 is null");
            return (Criteria) this;
        }

        public Criteria andEndrate2IsNotNull() {
            addCriterion("endRate2 is not null");
            return (Criteria) this;
        }

        public Criteria andEndrate2EqualTo(Long value) {
            addCriterion("endRate2 =", value, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2NotEqualTo(Long value) {
            addCriterion("endRate2 <>", value, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2GreaterThan(Long value) {
            addCriterion("endRate2 >", value, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2GreaterThanOrEqualTo(Long value) {
            addCriterion("endRate2 >=", value, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2LessThan(Long value) {
            addCriterion("endRate2 <", value, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2LessThanOrEqualTo(Long value) {
            addCriterion("endRate2 <=", value, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2In(List<Long> values) {
            addCriterion("endRate2 in", values, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2NotIn(List<Long> values) {
            addCriterion("endRate2 not in", values, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2Between(Long value1, Long value2) {
            addCriterion("endRate2 between", value1, value2, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndrate2NotBetween(Long value1, Long value2) {
            addCriterion("endRate2 not between", value1, value2, "endrate2");
            return (Criteria) this;
        }

        public Criteria andEndnum2IsNull() {
            addCriterion("endNum2 is null");
            return (Criteria) this;
        }

        public Criteria andEndnum2IsNotNull() {
            addCriterion("endNum2 is not null");
            return (Criteria) this;
        }

        public Criteria andEndnum2EqualTo(Integer value) {
            addCriterion("endNum2 =", value, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2NotEqualTo(Integer value) {
            addCriterion("endNum2 <>", value, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2GreaterThan(Integer value) {
            addCriterion("endNum2 >", value, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2GreaterThanOrEqualTo(Integer value) {
            addCriterion("endNum2 >=", value, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2LessThan(Integer value) {
            addCriterion("endNum2 <", value, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2LessThanOrEqualTo(Integer value) {
            addCriterion("endNum2 <=", value, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2In(List<Integer> values) {
            addCriterion("endNum2 in", values, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2NotIn(List<Integer> values) {
            addCriterion("endNum2 not in", values, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2Between(Integer value1, Integer value2) {
            addCriterion("endNum2 between", value1, value2, "endnum2");
            return (Criteria) this;
        }

        public Criteria andEndnum2NotBetween(Integer value1, Integer value2) {
            addCriterion("endNum2 not between", value1, value2, "endnum2");
            return (Criteria) this;
        }

        public Criteria andGuessname2IsNull() {
            addCriterion("guessName2 is null");
            return (Criteria) this;
        }

        public Criteria andGuessname2IsNotNull() {
            addCriterion("guessName2 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessname2EqualTo(String value) {
            addCriterion("guessName2 =", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotEqualTo(String value) {
            addCriterion("guessName2 <>", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2GreaterThan(String value) {
            addCriterion("guessName2 >", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2GreaterThanOrEqualTo(String value) {
            addCriterion("guessName2 >=", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2LessThan(String value) {
            addCriterion("guessName2 <", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2LessThanOrEqualTo(String value) {
            addCriterion("guessName2 <=", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2Like(String value) {
            addCriterion("guessName2 like", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotLike(String value) {
            addCriterion("guessName2 not like", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2In(List<String> values) {
            addCriterion("guessName2 in", values, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotIn(List<String> values) {
            addCriterion("guessName2 not in", values, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2Between(String value1, String value2) {
            addCriterion("guessName2 between", value1, value2, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotBetween(String value1, String value2) {
            addCriterion("guessName2 not between", value1, value2, "guessname2");
            return (Criteria) this;
        }

        public Criteria andResult2IsNull() {
            addCriterion("result2 is null");
            return (Criteria) this;
        }

        public Criteria andResult2IsNotNull() {
            addCriterion("result2 is not null");
            return (Criteria) this;
        }

        public Criteria andResult2EqualTo(String value) {
            addCriterion("result2 =", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2NotEqualTo(String value) {
            addCriterion("result2 <>", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2GreaterThan(String value) {
            addCriterion("result2 >", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2GreaterThanOrEqualTo(String value) {
            addCriterion("result2 >=", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2LessThan(String value) {
            addCriterion("result2 <", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2LessThanOrEqualTo(String value) {
            addCriterion("result2 <=", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2Like(String value) {
            addCriterion("result2 like", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2NotLike(String value) {
            addCriterion("result2 not like", value, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2In(List<String> values) {
            addCriterion("result2 in", values, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2NotIn(List<String> values) {
            addCriterion("result2 not in", values, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2Between(String value1, String value2) {
            addCriterion("result2 between", value1, value2, "result2");
            return (Criteria) this;
        }

        public Criteria andResult2NotBetween(String value1, String value2) {
            addCriterion("result2 not between", value1, value2, "result2");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNull() {
            addCriterion("hostName is null");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNotNull() {
            addCriterion("hostName is not null");
            return (Criteria) this;
        }

        public Criteria andHostnameEqualTo(String value) {
            addCriterion("hostName =", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotEqualTo(String value) {
            addCriterion("hostName <>", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThan(String value) {
            addCriterion("hostName >", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThanOrEqualTo(String value) {
            addCriterion("hostName >=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThan(String value) {
            addCriterion("hostName <", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThanOrEqualTo(String value) {
            addCriterion("hostName <=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLike(String value) {
            addCriterion("hostName like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotLike(String value) {
            addCriterion("hostName not like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameIn(List<String> values) {
            addCriterion("hostName in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotIn(List<String> values) {
            addCriterion("hostName not in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameBetween(String value1, String value2) {
            addCriterion("hostName between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotBetween(String value1, String value2) {
            addCriterion("hostName not between", value1, value2, "hostname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guess_result
     *
     * @mbg.generated do_not_delete_during_merge Sun May 24 17:27:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guess_result
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}