package com.lyl.webElf.domain;

import java.util.ArrayList;
import java.util.List;

public class GuessDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public GuessDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameidIsNull() {
            addCriterion("gameId is null");
            return (Criteria) this;
        }

        public Criteria andGameidIsNotNull() {
            addCriterion("gameId is not null");
            return (Criteria) this;
        }

        public Criteria andGameidEqualTo(String value) {
            addCriterion("gameId =", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotEqualTo(String value) {
            addCriterion("gameId <>", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidGreaterThan(String value) {
            addCriterion("gameId >", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidGreaterThanOrEqualTo(String value) {
            addCriterion("gameId >=", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLessThan(String value) {
            addCriterion("gameId <", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLessThanOrEqualTo(String value) {
            addCriterion("gameId <=", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidLike(String value) {
            addCriterion("gameId like", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotLike(String value) {
            addCriterion("gameId not like", value, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidIn(List<String> values) {
            addCriterion("gameId in", values, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotIn(List<String> values) {
            addCriterion("gameId not in", values, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidBetween(String value1, String value2) {
            addCriterion("gameId between", value1, value2, "gameid");
            return (Criteria) this;
        }

        public Criteria andGameidNotBetween(String value1, String value2) {
            addCriterion("gameId not between", value1, value2, "gameid");
            return (Criteria) this;
        }

        public Criteria andGuessname1IsNull() {
            addCriterion("guessName1 is null");
            return (Criteria) this;
        }

        public Criteria andGuessname1IsNotNull() {
            addCriterion("guessName1 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessname1EqualTo(String value) {
            addCriterion("guessName1 =", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotEqualTo(String value) {
            addCriterion("guessName1 <>", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1GreaterThan(String value) {
            addCriterion("guessName1 >", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1GreaterThanOrEqualTo(String value) {
            addCriterion("guessName1 >=", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1LessThan(String value) {
            addCriterion("guessName1 <", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1LessThanOrEqualTo(String value) {
            addCriterion("guessName1 <=", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1Like(String value) {
            addCriterion("guessName1 like", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotLike(String value) {
            addCriterion("guessName1 not like", value, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1In(List<String> values) {
            addCriterion("guessName1 in", values, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotIn(List<String> values) {
            addCriterion("guessName1 not in", values, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1Between(String value1, String value2) {
            addCriterion("guessName1 between", value1, value2, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname1NotBetween(String value1, String value2) {
            addCriterion("guessName1 not between", value1, value2, "guessname1");
            return (Criteria) this;
        }

        public Criteria andGuessname2IsNull() {
            addCriterion("guessName2 is null");
            return (Criteria) this;
        }

        public Criteria andGuessname2IsNotNull() {
            addCriterion("guessName2 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessname2EqualTo(String value) {
            addCriterion("guessName2 =", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotEqualTo(String value) {
            addCriterion("guessName2 <>", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2GreaterThan(String value) {
            addCriterion("guessName2 >", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2GreaterThanOrEqualTo(String value) {
            addCriterion("guessName2 >=", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2LessThan(String value) {
            addCriterion("guessName2 <", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2LessThanOrEqualTo(String value) {
            addCriterion("guessName2 <=", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2Like(String value) {
            addCriterion("guessName2 like", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotLike(String value) {
            addCriterion("guessName2 not like", value, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2In(List<String> values) {
            addCriterion("guessName2 in", values, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotIn(List<String> values) {
            addCriterion("guessName2 not in", values, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2Between(String value1, String value2) {
            addCriterion("guessName2 between", value1, value2, "guessname2");
            return (Criteria) this;
        }

        public Criteria andGuessname2NotBetween(String value1, String value2) {
            addCriterion("guessName2 not between", value1, value2, "guessname2");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNull() {
            addCriterion("hostName is null");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNotNull() {
            addCriterion("hostName is not null");
            return (Criteria) this;
        }

        public Criteria andHostnameEqualTo(String value) {
            addCriterion("hostName =", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotEqualTo(String value) {
            addCriterion("hostName <>", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThan(String value) {
            addCriterion("hostName >", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThanOrEqualTo(String value) {
            addCriterion("hostName >=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThan(String value) {
            addCriterion("hostName <", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThanOrEqualTo(String value) {
            addCriterion("hostName <=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLike(String value) {
            addCriterion("hostName like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotLike(String value) {
            addCriterion("hostName not like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameIn(List<String> values) {
            addCriterion("hostName in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotIn(List<String> values) {
            addCriterion("hostName not in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameBetween(String value1, String value2) {
            addCriterion("hostName between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotBetween(String value1, String value2) {
            addCriterion("hostName not between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andBoxtitleIsNull() {
            addCriterion("boxTitle is null");
            return (Criteria) this;
        }

        public Criteria andBoxtitleIsNotNull() {
            addCriterion("boxTitle is not null");
            return (Criteria) this;
        }

        public Criteria andBoxtitleEqualTo(String value) {
            addCriterion("boxTitle =", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleNotEqualTo(String value) {
            addCriterion("boxTitle <>", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleGreaterThan(String value) {
            addCriterion("boxTitle >", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleGreaterThanOrEqualTo(String value) {
            addCriterion("boxTitle >=", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleLessThan(String value) {
            addCriterion("boxTitle <", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleLessThanOrEqualTo(String value) {
            addCriterion("boxTitle <=", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleLike(String value) {
            addCriterion("boxTitle like", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleNotLike(String value) {
            addCriterion("boxTitle not like", value, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleIn(List<String> values) {
            addCriterion("boxTitle in", values, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleNotIn(List<String> values) {
            addCriterion("boxTitle not in", values, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleBetween(String value1, String value2) {
            addCriterion("boxTitle between", value1, value2, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andBoxtitleNotBetween(String value1, String value2) {
            addCriterion("boxTitle not between", value1, value2, "boxtitle");
            return (Criteria) this;
        }

        public Criteria andGuessresult1IsNull() {
            addCriterion("guessResult1 is null");
            return (Criteria) this;
        }

        public Criteria andGuessresult1IsNotNull() {
            addCriterion("guessResult1 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessresult1EqualTo(String value) {
            addCriterion("guessResult1 =", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1NotEqualTo(String value) {
            addCriterion("guessResult1 <>", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1GreaterThan(String value) {
            addCriterion("guessResult1 >", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1GreaterThanOrEqualTo(String value) {
            addCriterion("guessResult1 >=", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1LessThan(String value) {
            addCriterion("guessResult1 <", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1LessThanOrEqualTo(String value) {
            addCriterion("guessResult1 <=", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1Like(String value) {
            addCriterion("guessResult1 like", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1NotLike(String value) {
            addCriterion("guessResult1 not like", value, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1In(List<String> values) {
            addCriterion("guessResult1 in", values, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1NotIn(List<String> values) {
            addCriterion("guessResult1 not in", values, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1Between(String value1, String value2) {
            addCriterion("guessResult1 between", value1, value2, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult1NotBetween(String value1, String value2) {
            addCriterion("guessResult1 not between", value1, value2, "guessresult1");
            return (Criteria) this;
        }

        public Criteria andGuessresult2IsNull() {
            addCriterion("guessResult2 is null");
            return (Criteria) this;
        }

        public Criteria andGuessresult2IsNotNull() {
            addCriterion("guessResult2 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessresult2EqualTo(String value) {
            addCriterion("guessResult2 =", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2NotEqualTo(String value) {
            addCriterion("guessResult2 <>", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2GreaterThan(String value) {
            addCriterion("guessResult2 >", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2GreaterThanOrEqualTo(String value) {
            addCriterion("guessResult2 >=", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2LessThan(String value) {
            addCriterion("guessResult2 <", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2LessThanOrEqualTo(String value) {
            addCriterion("guessResult2 <=", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2Like(String value) {
            addCriterion("guessResult2 like", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2NotLike(String value) {
            addCriterion("guessResult2 not like", value, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2In(List<String> values) {
            addCriterion("guessResult2 in", values, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2NotIn(List<String> values) {
            addCriterion("guessResult2 not in", values, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2Between(String value1, String value2) {
            addCriterion("guessResult2 between", value1, value2, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andGuessresult2NotBetween(String value1, String value2) {
            addCriterion("guessResult2 not between", value1, value2, "guessresult2");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andRate1IsNull() {
            addCriterion("rate1 is null");
            return (Criteria) this;
        }

        public Criteria andRate1IsNotNull() {
            addCriterion("rate1 is not null");
            return (Criteria) this;
        }

        public Criteria andRate1EqualTo(String value) {
            addCriterion("rate1 =", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1NotEqualTo(String value) {
            addCriterion("rate1 <>", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1GreaterThan(String value) {
            addCriterion("rate1 >", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1GreaterThanOrEqualTo(String value) {
            addCriterion("rate1 >=", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1LessThan(String value) {
            addCriterion("rate1 <", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1LessThanOrEqualTo(String value) {
            addCriterion("rate1 <=", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1Like(String value) {
            addCriterion("rate1 like", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1NotLike(String value) {
            addCriterion("rate1 not like", value, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1In(List<String> values) {
            addCriterion("rate1 in", values, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1NotIn(List<String> values) {
            addCriterion("rate1 not in", values, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1Between(String value1, String value2) {
            addCriterion("rate1 between", value1, value2, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate1NotBetween(String value1, String value2) {
            addCriterion("rate1 not between", value1, value2, "rate1");
            return (Criteria) this;
        }

        public Criteria andRate2IsNull() {
            addCriterion("rate2 is null");
            return (Criteria) this;
        }

        public Criteria andRate2IsNotNull() {
            addCriterion("rate2 is not null");
            return (Criteria) this;
        }

        public Criteria andRate2EqualTo(String value) {
            addCriterion("rate2 =", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2NotEqualTo(String value) {
            addCriterion("rate2 <>", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2GreaterThan(String value) {
            addCriterion("rate2 >", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2GreaterThanOrEqualTo(String value) {
            addCriterion("rate2 >=", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2LessThan(String value) {
            addCriterion("rate2 <", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2LessThanOrEqualTo(String value) {
            addCriterion("rate2 <=", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2Like(String value) {
            addCriterion("rate2 like", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2NotLike(String value) {
            addCriterion("rate2 not like", value, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2In(List<String> values) {
            addCriterion("rate2 in", values, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2NotIn(List<String> values) {
            addCriterion("rate2 not in", values, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2Between(String value1, String value2) {
            addCriterion("rate2 between", value1, value2, "rate2");
            return (Criteria) this;
        }

        public Criteria andRate2NotBetween(String value1, String value2) {
            addCriterion("rate2 not between", value1, value2, "rate2");
            return (Criteria) this;
        }

        public Criteria andGuessnum1IsNull() {
            addCriterion("guessNum1 is null");
            return (Criteria) this;
        }

        public Criteria andGuessnum1IsNotNull() {
            addCriterion("guessNum1 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessnum1EqualTo(String value) {
            addCriterion("guessNum1 =", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1NotEqualTo(String value) {
            addCriterion("guessNum1 <>", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1GreaterThan(String value) {
            addCriterion("guessNum1 >", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1GreaterThanOrEqualTo(String value) {
            addCriterion("guessNum1 >=", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1LessThan(String value) {
            addCriterion("guessNum1 <", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1LessThanOrEqualTo(String value) {
            addCriterion("guessNum1 <=", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1Like(String value) {
            addCriterion("guessNum1 like", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1NotLike(String value) {
            addCriterion("guessNum1 not like", value, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1In(List<String> values) {
            addCriterion("guessNum1 in", values, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1NotIn(List<String> values) {
            addCriterion("guessNum1 not in", values, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1Between(String value1, String value2) {
            addCriterion("guessNum1 between", value1, value2, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum1NotBetween(String value1, String value2) {
            addCriterion("guessNum1 not between", value1, value2, "guessnum1");
            return (Criteria) this;
        }

        public Criteria andGuessnum2IsNull() {
            addCriterion("guessNum2 is null");
            return (Criteria) this;
        }

        public Criteria andGuessnum2IsNotNull() {
            addCriterion("guessNum2 is not null");
            return (Criteria) this;
        }

        public Criteria andGuessnum2EqualTo(String value) {
            addCriterion("guessNum2 =", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2NotEqualTo(String value) {
            addCriterion("guessNum2 <>", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2GreaterThan(String value) {
            addCriterion("guessNum2 >", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2GreaterThanOrEqualTo(String value) {
            addCriterion("guessNum2 >=", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2LessThan(String value) {
            addCriterion("guessNum2 <", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2LessThanOrEqualTo(String value) {
            addCriterion("guessNum2 <=", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2Like(String value) {
            addCriterion("guessNum2 like", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2NotLike(String value) {
            addCriterion("guessNum2 not like", value, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2In(List<String> values) {
            addCriterion("guessNum2 in", values, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2NotIn(List<String> values) {
            addCriterion("guessNum2 not in", values, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2Between(String value1, String value2) {
            addCriterion("guessNum2 between", value1, value2, "guessnum2");
            return (Criteria) this;
        }

        public Criteria andGuessnum2NotBetween(String value1, String value2) {
            addCriterion("guessNum2 not between", value1, value2, "guessnum2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guess_data
     *
     * @mbg.generated do_not_delete_during_merge Sun May 24 17:27:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guess_data
     *
     * @mbg.generated Sun May 24 17:27:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}