package com.lyl.webElf.domain;

import java.util.Date;

public class LiveItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.id
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.num
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.title
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.isOnTv
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String isontv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.isGuess
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String isguess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.hostName
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String hostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.url
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.pageNo
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String pageno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.createTime
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.updateTime
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.isRecordingGuessData
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String isrecordingguessdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_item.enable
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    private String enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.id
     *
     * @return the value of live_item.id
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.id
     *
     * @param id the value for live_item.id
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.num
     *
     * @return the value of live_item.num
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.num
     *
     * @param num the value for live_item.num
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.title
     *
     * @return the value of live_item.title
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.title
     *
     * @param title the value for live_item.title
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.isOnTv
     *
     * @return the value of live_item.isOnTv
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getIsontv() {
        return isontv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.isOnTv
     *
     * @param isontv the value for live_item.isOnTv
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setIsontv(String isontv) {
        this.isontv = isontv == null ? null : isontv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.isGuess
     *
     * @return the value of live_item.isGuess
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getIsguess() {
        return isguess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.isGuess
     *
     * @param isguess the value for live_item.isGuess
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setIsguess(String isguess) {
        this.isguess = isguess == null ? null : isguess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.hostName
     *
     * @return the value of live_item.hostName
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.hostName
     *
     * @param hostname the value for live_item.hostName
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.url
     *
     * @return the value of live_item.url
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.url
     *
     * @param url the value for live_item.url
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.pageNo
     *
     * @return the value of live_item.pageNo
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getPageno() {
        return pageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.pageNo
     *
     * @param pageno the value for live_item.pageNo
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setPageno(String pageno) {
        this.pageno = pageno == null ? null : pageno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.createTime
     *
     * @return the value of live_item.createTime
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.createTime
     *
     * @param createtime the value for live_item.createTime
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.updateTime
     *
     * @return the value of live_item.updateTime
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.updateTime
     *
     * @param updatetime the value for live_item.updateTime
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.isRecordingGuessData
     *
     * @return the value of live_item.isRecordingGuessData
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getIsrecordingguessdata() {
        return isrecordingguessdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.isRecordingGuessData
     *
     * @param isrecordingguessdata the value for live_item.isRecordingGuessData
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setIsrecordingguessdata(String isrecordingguessdata) {
        this.isrecordingguessdata = isrecordingguessdata == null ? null : isrecordingguessdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_item.enable
     *
     * @return the value of live_item.enable
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_item.enable
     *
     * @param enable the value for live_item.enable
     *
     * @mbg.generated Sun May 24 17:26:49 CST 2020
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }
}